apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: web
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      serviceAccountName: web-deployment-sa
      containers:
        - name: web-app
          image: public.ecr.aws/t4j8r4w0/web:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "web-deployment-aws-secrets"
